default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: mario_development

test:
  <<: *default
  database: mario_test

production:
  <<: *default
  database: mario_production
  username: mario
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
